### ISSUE TITLE
Unable to open links on a external browser 

### ISSUE THREAD

**Issue by MrKaon** [Blatzar/Redited#10]
Internal browser works fine, but if you set it in setting to open links in external one, it fails to do so. With prompt "No apps can perform this action".

**Comment by Blatzar** [comment]
I have not modified that. It's a base reddit issue. Install a browser or something.

**Comment by MrKaon** [comment]
> I have not modified that. It's a base reddit issue. Install a browser or something.

So Reddit issue then, as I do have a browser on my phone. (Chrome & Firefox)
