### ISSUE TITLE
any ETA on an update?

### ISSUE THREAD

**Issue by subby2006** [Blatzar/Redited#4]
Seems like Reddit changed something on their end and now half of the searches made are returned empty or is stuck constantly loading. This doesn't seem to happen on the latest base from the Google Play store and just started happening about a week ago. Any chance we could get a base bump? Last update was almost a month ago

**Comment by Blatzar** [comment]
Now: https://github.com/Blatzar/Redited/releases/tag/2022.27.0.0

**Comment by subby2006** [comment]
Thank you so much Blatzar!
