### ISSUE TITLE
Popular-tab content differs from the original/official app and web versions

### ISSUE THREAD

**Issue by Visiraptor** [Blatzar/Redited#6]
Hello Blatzar, 

first, thanks for your work. This seems to be working, but...
just wanted to note that the "Redited" app shows different content in the "popular"-tab (at least for me) in comparison to the "original" Reddit app. This is also true for web version, so there might be something "uncorrect" with the Redited app (a wild guess: Maybe country-specific-things or "non-existing-premium-sideeffect"?). Additionally you cannot see the location tab/list on the popular-tab on your app. 

Last but not least: A request: Is it possible to add "Redited" to F-Droid please? If yes, please do it :D. Thank you. Keep up the good work!

PS: Oh and my "history" got deleted/cleared but I am not sure if "Redited" app is the reason for it, so I will keep quit :).

**Comment by Blatzar** [comment]
I've only done some fairly basic editing of the official app which is closed source. F-droid only accepts open source apps and this one isn't :(

I don't see how my editing would affect the trending tab or stuff in general not related to ads so I'm thinking this is due different base reddit versions.

**Comment by Visiraptor** [comment]
Hmm, I do not know how this things work, but it is unusually that the content is different even though the base versions are the same. I am using the official reddit android app since ever (and always up2date). Yesterday I found "Redited" and wanted to give it a try. Yeah, it blockes the "sponsored"-things, but changing my preferred content (besides the deleted history) really annoys me. So if this cannot be fixed I unfortunately have to go back to the official reddit app (with ads etc.). Maybe you (or someone) else could help somehow?

**Comment by Blatzar** [comment]
Got no idea 🤷
try some older apks of mine I guess

**Comment by Visiraptor** [comment]
Thanks for the hint :). I tried all of your apps available releases (well, there are actually "just 3"). Only one version has the option to choose the location and sorting on the "popular-tab". Yes, the very first version (2022.21.0) has the option to change the content to what I am used to (on web and original app). Unfortunately that version does not block as much things as your newest version (2022.27.0). So is there any possibility you can match/compare those codes?
 
PS: Sorry, I previously wrote that it is about the "trending"-tab, but it is about the "popular"-tab (my bad, translation error, my English is bad I know).

**Comment by Visiraptor** [comment]
A newer base version was released. Could you please add your patch to that one? Or maybe you could apply your patch to your first release (2022.21.0) since that version is the one with the correct headers on the popular-tab. Thank you in advance.

**Comment by Visiraptor** [comment]
Sorry, for double-post but since you have released two new versions a few hours ago I wanted to write again (since the thread cannot be closed yet). 

Above the text "Trending today" and under the tab "Popular" there is a section with sort by, location, and post view. This is the section I want to have on the newest app with all your patches. Is that possible for version 2022.31.0 (latest release) and future releases? 

It is working/showing for "2021.43.0" and also "2022.21.0", but not for "2022.23.0", "2022.27.0" & "2022.31.0", so I would guess that something has changed after version "22.21". Maybe you could have a look at it. 

Thank you for your good work. 

PS: I'm always using "arm64_v8a.apk" if this is an important information for you.

**Comment by Blatzar** [comment]
This is just something with the base app and not my patches because I applied the exact same patches on 2022.31.0 and 2021.43.0

**Comment by Visiraptor** [comment]
Okay. Hope Reddit will do something to the base app in the future but it seems hopeless somehow (since they won't take a step "back to the old style/versions/codes"). 
Thank you. This thread can now be closed I guess (since you gave the final answer).
